sudo: required

language: python
python:
  - "3.6"

services:
  - docker

# command to install dependencies
before_install:
  - docker build -t graik/biskit .

install:
  - pip install coverage coveralls
  
# command to run tests
script:
  docker run -v "$PWD:/app" -t graik/biskit coverage run biskit/test.py -e fails old extra

after_success:
  ## replace absolute /app/biskit/ path in coverage result
  ## by `pwd`/biskit
  - sed 's@/app/@'"$PWD"'/@g' .coverage
  - coveralls

after_failure:
  - sed -i 's@/app/@'"$PWD"'/@g' .coverage
  - coveralls
